# Generated by Django 2.2.2 on 2019-06-13 07:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dterp_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Order_Details',
            new_name='OrderDetails',
        ),
        migrations.AddField(
            model_name='employee',
            name='address',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='employee',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='dterp_app.Employee'),
        ),
        migrations.AddField(
            model_name='product',
            name='inventory',
            field=models.IntegerField(default=0),
        ),
    ]
